"""Adição de modelos de Patrimônio e Movimentação Financeira

Revision ID: 1931760c74ec
Revises: 
Create Date: 2025-06-23 01:12:28.486911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1931760c74ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacao_financeira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('origem_tipo', sa.String(length=50), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_aquisicao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compra_patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('status_pagamento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['patrimonio_id'], ['patrimonio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=50), nullable=False))
        batch_op.drop_column('nf_entrada')

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('status_pagamento')

    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nf_entrada', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('status_pagamento')
        batch_op.drop_column('forma_pagamento')

    op.drop_table('compra_patrimonio')
    op.drop_table('patrimonio')
    op.drop_table('movimentacao_financeira')
    # ### end Alembic commands ###
