"""Retirando telefone do Fornecedor

Revision ID: 2505ba610fac
Revises: 682ae3a01880
Create Date: 2025-04-24 23:40:55.876950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2505ba610fac'
down_revision = '682ae3a01880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
