"""alterações em Cliente

Revision ID: 682ae3a01880
Revises: 
Create Date: 2025-04-24 23:38:08.663567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '682ae3a01880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=200), nullable=True))
        batch_op.drop_column('telefone')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
